# utils/pdf_generator.py
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from datetime import datetime
import os
import uuid
from typing import Any


def _flatten_content(obj: Any, indent: int = 0) -> str:
    """
    Convert nested structures (dicts, lists, strings, numbers) into a readable string.
    """
    spacer = "  " * indent
    if obj is None:
        return ""
    if isinstance(obj, str):
        return obj
    if isinstance(obj, (int, float, bool)):
        return str(obj)
    if isinstance(obj, list) or isinstance(obj, tuple):
        lines = []
        for item in obj:
            flattened = _flatten_content(item, indent + 1)
            # bullet each top-level list item
            prefix = "\n" + spacer + "- " if indent >= 0 else ""
            lines.append(prefix + flattened.strip())
        return "\n".join(lines)
    if isinstance(obj, dict):
        lines = []
        for k, v in obj.items():
            val = _flatten_content(v, indent + 1).strip()
            lines.append(f"\n{spacer}{k}: {val}")
        return "\n".join(lines)
    # fallback: use repr
    return repr(obj)


def _sanitize_for_paragraph(text: str) -> str:
    """
    Prepare plain text for ReportLab Paragraph:
    - convert newlines to <br/>
    - convert simple markdown **bold** and __italic__ to <b> and <i>
    """
    if text is None:
        return ""
    # Ensure text is a string
    text = str(text)

    # Replace HTML-sensitive characters (basic)
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    # Convert markdown-like bold/italic into tags
    # Simple approach: replace **...** and __...__ (non-greedy)
    import re

    # bold
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    # italic
    text = re.sub(r"__(.+?)__", r"<i>\1</i>", text)

    # preserve paragraphs / line breaks
    text = text.replace("\n", "<br/>")
    return text


def generate_report(results: dict, query: str = "", duration: float = 0) -> str:
    """
    Generate a wrapped, nicely formatted PDF from `results`.
    `results` is expected to be a dict mapping agent_name -> agent_content (which may be dict/list/str).
    Returns the filename of the generated PDF.
    """
    reports_dir = "reports"
    os.makedirs(reports_dir, exist_ok=True)

    session_id = str(uuid.uuid4())
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    filename = (
        f"{reports_dir}/report_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.pdf"
    )

    # Create document
    doc = SimpleDocTemplate(filename, pagesize=A4)
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Heading1"], alignment=TA_CENTER, spaceAfter=20
    )
    section_header = ParagraphStyle(
        "SectionHeader", parent=styles["Heading2"], spaceBefore=12, spaceAfter=6
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"], fontSize=11, leading=14
    )

    story = []
    story.append(Paragraph("Agentic AI Research Summary Report", title_style))
    story.append(Paragraph(f"<b>Session ID:</b> {session_id}", body_style))
    if query:
        story.append(
            Paragraph(f"<b>Query:</b> {_sanitize_for_paragraph(query)}", body_style)
        )
    story.append(Paragraph(f"<b>Generated:</b> {timestamp}", body_style))
    if duration is not None:
        story.append(
            Paragraph(
                f"<b>Total Execution Time:</b> {round(duration, 2)} sec", body_style
            )
        )
    story.append(Spacer(1, 12))

    # Add each agent section with proper wrapping and flattened content
    for agent_name, content in results.items():
        story.append(Paragraph(agent_name.replace("_", " ").title(), section_header))
        # Flatten nested structures to text
        flat = _flatten_content(content)
        safe_text = _sanitize_for_paragraph(flat)
        # If the content is long, split into multiple paragraphs by double newlines
        # but Paragraph will handle wrapping; still keep it simple
        story.append(Paragraph(safe_text, body_style))
        story.append(Spacer(1, 12))

    story.append(PageBreak())

    # Optional: small footer page with metadata
    footer_header = Paragraph("Metadata", section_header)
    footer_body = Paragraph(
        _sanitize_for_paragraph(
            f"Generated by Agentic AI (phi3 via Ollama) on {timestamp}.\nSession ID: {session_id}"
        ),
        body_style,
    )
    story.append(footer_header)
    story.append(footer_body)

    # Build the PDF
    doc.build(story)
    return filename
